steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/palash315/docker_d', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/palash315/docker_d']

- name: 'gcr.io/cloud-builders/docker'
  args: ['kubectl','set','image', 'palash315/docker_d', 'mynode=gcr.io/sit737-23t1-shah-ddcd0bc/palash315/docker_d']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'