steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'australia-southeast1-gcr.io/$PROJECT_ID/palash315/docker_d', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'australia-southeast1-gcr.io/$PROJECT_ID/palash315/docker_d']