steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["-c", "docker build --build-arg 'CONTAINER_PRIVATE_KEY=$$PRIVATE_KEY' --build-arg 'CONTAINER_PUBLIC_KEY=$$PUBLIC_KEY' -t gcr.io/${PROJECT_ID}/palash315/docker_d ."]
  # args: ['build', '-t', 'australia-southeast1-gcr.io/$PROJECT_ID/palash315/docker_d', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'australia-southeast1-gcr.io/$PROJECT_ID/palash315/docker_d']