steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'australia-southeast1-gcr.io/sit737-23t1-shah-ddcd0bc/palash315/docker_d', '.']

- name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'australia-southeast1-gcr.io/sit737-23t1-shah-ddcd0bc/palash315/docker_d']