steps:
# Build Docker Image
- name: 'gcr.io/sit737-23t1-shah-ddcd0bc/palash315/docker_d'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/palash315/docker_d:$COMMIT_SHA', '.']


# Docker Push
- name: 'gcr.io/sit737-23t1-shah-ddcd0bc/palash315/docker_d'
  args: ['push', 'gcr.io/${PROJECT_ID}/palash315/docker_d:$COMMIT_SHA']


- name: 'gcr.io/sit737-23t1-shah-ddcd0bc/palash315/docker_d'
  args: ['set', 'image', 'palash315/docker_d', 'mynode=gcr.io/sit737-23t1-shah-ddcd0bc/palash315/docker_d:$COMMIT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'