apiVersion: apps/v1
kind: Deployment
metadata:
  name: palash10.2D
  labels:
    app: myapp10.2D
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: mynode
        image: palash315/docker_d
        ports:
        - containerPort: 8080